using System;
using System.Collections;
using System.Collections.Generic;

namespace CurtinUniversity.MolecularDynamics.Model {

    public enum Element {

        H,
        He,
        Li,
        Be,
        B,
        C,
        N,
        O,
        F,
        Ne,
        Na,
        Mg,
        Al,
        Si,
        P,
        S,
        Cl,
        Ar,
        K,
        Ca,
        Sc,
        Ti,
        V,
        Cr,
        Mn,
        Fe,
        Co,
        Ni,
        Cu,
        Zn,
        Ga,
        Ge,
        As,
        Se,
        Br,
        Kr,
        Rb,
        Sr,
        Y,
        Zr,
        Nb,
        Mo,
        Tc,
        Ru,
        Rh,
        Pd,
        Ag,
        Cd,
        In,
        Sn,
        Sb,
        Te,
        I,
        Xe,
        Cs,
        Ba,
        La,
        Ce,
        Pr,
        Nd,
        Pm,
        Sm,
        Eu,
        Gd,
        Tb,
        Dy,
        Ho,
        Er,
        Tm,
        Yb,
        Lu,
        Hf,
        Ta,
        W,
        Re,
        Os,
        Ir,
        Pt,
        Au,
        Hg,
        Tl,
        Pb,
        Bi,
        Po,
        At,
        Rn,
        Fr,
        Ra,
        Ac,
        Th,
        Pa,
        U,
        Np,
        Pu,
        Am,
        Cm,
        Bk,
        Cf,
        Es,
        Fm,
        Md,
        No,
        Lr,
        Rf,
        Db,
        Sg,
        Bh,
        Hs,
        Mt,
        Ds,
        Rg,
        Cn,
        Nh,
        Fl,
        Mc,
        Lv,
        Ts,
        Og,
        Other,
    }

    public static class ChemicalElement {

        // Molecular size in nanometers
        public static Dictionary<Element, float> AtomicRadius = new Dictionary<Element, float>() {

            { Element.H,  0.053f },
            { Element.He, 0.031f },
            { Element.Li, 0.167f },
            { Element.Be, 0.112f },
            { Element.B,  0.087f },
            { Element.C,  0.067f },
            { Element.N,  0.056f },
            { Element.O,  0.048f },
            { Element.F,  0.042f },
            { Element.Ne, 0.038f },
            { Element.Na, 0.190f },
            { Element.Mg, 0.145f },
            { Element.Al, 0.118f },
            { Element.Si, 0.111f },
            { Element.P,  0.098f },
            { Element.S,  0.088f },
            { Element.Cl, 0.079f },
            { Element.Ar, 0.071f },
            { Element.K,  0.243f },
            { Element.Ca, 0.194f },
            { Element.Sc, 0.184f },
            { Element.Ti, 0.176f },
            { Element.V,  0.171f },
            { Element.Cr, 0.166f },
            { Element.Mn, 0.161f },
            { Element.Fe, 0.156f },
            { Element.Co, 0.152f },
            { Element.Ni, 0.149f },
            { Element.Cu, 0.145f },
            { Element.Zn, 0.142f },
            { Element.Ga, 0.136f },
            { Element.Ge, 0.125f },
            { Element.As, 0.114f },
            { Element.Se, 0.103f },
            { Element.Br, 0.094f },
            { Element.Kr, 0.088f },
            { Element.Rb, 0.265f },
            { Element.Sr, 0.219f },
            { Element.Y,  0.212f },
            { Element.Zr, 0.206f },
            { Element.Nb, 0.198f },
            { Element.Mo, 0.190f },
            { Element.Tc, 0.183f },
            { Element.Ru, 0.178f },
            { Element.Rh, 0.173f },
            { Element.Pd, 0.169f },
            { Element.Ag, 0.165f },
            { Element.Cd, 0.161f },
            { Element.In, 0.156f },
            { Element.Sn, 0.145f },
            { Element.Sb, 0.133f },
            { Element.Te, 0.123f },
            { Element.I,  0.115f },
            { Element.Xe, 0.108f },
            { Element.Cs, 0.298f },
            { Element.Ba, 0.253f },
            { Element.La, 0.195f },
            { Element.Ce, 0.185f },
            { Element.Pr, 0.247f },
            { Element.Nd, 0.206f },
            { Element.Pm, 0.205f },
            { Element.Sm, 0.238f },
            { Element.Eu, 0.231f },
            { Element.Gd, 0.233f },
            { Element.Tb, 0.225f },
            { Element.Dy, 0.228f },
            { Element.Ho, 0.226f },
            { Element.Er, 0.226f },
            { Element.Tm, 0.222f },
            { Element.Yb, 0.222f },
            { Element.Lu, 0.217f },
            { Element.Hf, 0.208f },
            { Element.Ta, 0.200f },
            { Element.W,  0.193f },
            { Element.Re, 0.188f },
            { Element.Os, 0.185f },
            { Element.Ir, 0.180f },
            { Element.Pt, 0.177f },
            { Element.Au, 0.174f },
            { Element.Hg, 0.171f },
            { Element.Tl, 0.156f },
            { Element.Pb, 0.154f },
            { Element.Bi, 0.143f },
            { Element.Po, 0.135f },
            { Element.At, 0.127f },
            { Element.Rn, 0.120f },
            { Element.Fr, 0.120f },    // unknown, set to Rn as default
            { Element.Ra, 0.120f },    // unknowm, set to Rn as default 
            { Element.Ac, 0.195f },
            { Element.Th, 0.180f },
            { Element.Pa, 0.180f },
            { Element.U,  0.175f },
            { Element.Np, 0.175f },
            { Element.Pu, 0.175f },
            { Element.Am, 0.175f },
            { Element.Cm, 0.175f },    // unknowm, set to Am as default
            { Element.Other, 0.05f },  // size for atoms not found
        };


        // VDW Radius in Nanometers
        public static Dictionary<Element, float> VDWRadius = new Dictionary<Element, float>() {

           { Element.H,  0.120f },
           { Element.He, 0.140f },
           { Element.Li, 0.182f },
           { Element.Be, 0.153f },
           { Element.B,  0.192f },
           { Element.C,  0.170f },
           { Element.N,  0.155f },
           { Element.O,  0.152f },
           { Element.F,  0.147f },
           { Element.Ne, 0.154f },
           { Element.Na, 0.227f },
           { Element.Mg, 0.173f },
           { Element.Al, 0.184f },
           { Element.Si, 0.210f },
           { Element.P,  0.180f },
           { Element.S,  0.180f },
           { Element.Cl, 0.175f },
           { Element.Ar, 0.188f },
           { Element.K,  0.275f },
           { Element.Ca, 0.231f },
           { Element.Sc, 0.211f },
           { Element.Ni, 0.163f },
           { Element.Cu, 0.140f },
           { Element.Zn, 0.139f },
           { Element.Ga, 0.187f },
           { Element.Ge, 0.211f },
           { Element.As, 0.185f },
           { Element.Se, 0.190f },
           { Element.Br, 0.185f },
           { Element.Kr, 0.202f },
           { Element.Rb, 0.303f },
           { Element.Sr, 0.249f },
           { Element.Pd, 0.163f },
           { Element.Ag, 0.172f },
           { Element.Cd, 0.158f },
           { Element.In, 0.193f },
           { Element.Sn, 0.217f },
           { Element.Sb, 0.206f },
           { Element.Te, 0.206f },
           { Element.I,  0.198f },
           { Element.Xe, 0.216f },
           { Element.Cs, 0.343f },
           { Element.Ba, 0.268f },
           { Element.Pt, 0.175f },
           { Element.Au, 0.166f },
           { Element.Hg, 0.155f },
           { Element.Tl, 0.196f },
           { Element.Pb, 0.202f },
           { Element.Bi, 0.207f },
           { Element.Po, 0.197f },
           { Element.At, 0.202f },
           { Element.Rn, 0.220f },
           { Element.Fr, 0.348f },
           { Element.Ra, 0.283f },
           { Element.U,  0.186f },
           { Element.Other, 0.15f },
        };
    }
}
